function Puma(e,h){var f=Puma.parseCache,d;f[e]?d=f[e]:(d=Puma.Parser.parse(e),f[e]=d,f.push(e),f.length>Puma.parseCacheSize&&(f[f.shift()]=void 0));return d.evaluate(h||document)}Puma.parseCache=[];Puma.parseCacheSize=100;
Puma.AST={Tag:function(e){this.value=e;this.evaluate=function(h){h=h.getElementsByTagName(e);if(h instanceof Object)return[].slice.call(h);return Puma.arrayFilter(h,function(){return!0})}},BinOp:function(e,h,f){this.value=e;this.left=h;this.right=f;this.evaluate=function(d){var c=Puma.operators.binary[e],a=[],b,g;if(c.noIter)return c(this.left,this.right,d);b=d.getElementsByTagName("*");for(g=b.length;g--;)c(b[g],this.left,this.right,d)&&a.push(b[g]);return a}},UnOp:function(e,h){this.value=e;this.right=
h;this.evaluate=function(f){var d=Puma.operators.unary[e],c=[],a,b;if(d.noIter)return d(this.right,f);a=f.getElementsByTagName("*");for(b=a.length;b--;)d(a[b],this.right,f)&&c.push(a[b]);return c}}};
Puma.Scanner={tokenize:function(e){function h(b,g){return{type:b,value:g,from:a,to:c,error:function(b){throw Error(b);}}}function f(b){return(b>="a"&&b<="z"||b>="A"&&b<="Z"||o.indexOf(b)>=0)&&b}for(var d=e.charAt(0),c=0,a,b,g=e.length,n=[],o="0123456789-_";d;)if(a=c,d==" "){var d=e.charAt(++c),i=e.charAt(c-2);(f(d)||d=="*"||Puma.operators.unary[d])&&(f(i)||i=="*")&&n.push(h("op"," "))}else if(f(d)){b=[d];for(++c;;)if(d=e.charAt(c),f(d))b.push(d),++c;else break;n.push(h("ident",b.join("")))}else if(d==
'"'||d=="'"){b=[];for(i=d;;){d=e.charAt(++c);d<" "&&h("ident",b.join("")).error("Bad string");if(d==i)break;d=="\\"&&(++c>=g&&h("ident",b.join("")).error("Bad string"),d="\\"+e.charAt(c));b.push(d)}n.push(h("ident",b.join("")));d=e.charAt(++c)}else if(d=="*"&&e.charAt(c+1)!="=")n.push(h("ident",d)),d=e.charAt(++c);else{b=[d];d=e.charAt(++c);i=e.charAt(c-1);if((d=="*"||!f(d))&&d!=" "&&i!="["&&i!="]"&&i!="("&&i!=")"&&d!='"'&&d!="'")b.push(d),d=e.charAt(++c);n.push(h("op",b.join("")))}return n}};
Puma.Parser={parse:function(e){function h(c){c&&g.id!=c&&g.error("Expected "+c+", not "+g.id);if(o>=n.length)g=b["(end)"];else{var c=n[o++],a=c.value,e=c.type,i=n[o-2],d,f;if(e=="ident")d=new Puma.AST.Tag(a),d.nud=function(){return this},d.led=null,d.lbp=0;else if(e=="op")for(f in b[a]||c.error("Unknown operator "+a),d=Puma.operators.unary[a]&&(!i||i.type=="op"&&i.value!="]"&&i.value!=")")?new Puma.AST.UnOp(a,c.right):new Puma.AST.BinOp(a,c.right,c.left),b[a])d[f]=b[a][f];else c.error("Unexpected token "+
a);g=d;g.from=c.from;g.to=c.to;g.value=g.id=a;g.arity=e;g.error=c.error;return g}}function f(b){var c,a=g;h();for(c=a.nud();b<g.lbp;)a=g,h(),c=a.led(c);return c}function d(g,c){var c=c||0,a=b[g];if(a){if(c>=a.lbp)a.lbp=c}else a={error:function(b){throw Error(b);},nud:function(){this.error("Undefined. "+g)},led:function(){this.error("Missing operator.")},lbp:c},a.id=a.value=g,b[g]=a;return a}function c(b,g,c){b=d(b,g);b.led=c||function(b){this.left=b;this.right=f(g);this.arity="binary";return this};
return b}function a(b,g){d(b).nud=g||function(){this.right=f(10);this.arity="unary";return this}}var b={},g,n=Puma.Scanner.tokenize(e),o=0,i;d("]");d(")");d("(end)");d("(ident)");for(i in Puma.operators.binary)c(i,Puma.operators.binary[i].precendence||10);c("[",20,function(b){this.left=b;this.right=f(0);this.arity="binary";h("]");return this});c("(",20,function(b){this.left=b;this.right=f(0);this.arity="binary";h(")");return this});for(i in Puma.operators.unary)a(i);a("[",function(){this.right=f(0);
this.arity="unary";h("]");return this});h();i=f(0);h("(end)");i.query=e;i.tokens=n;return i}};
(function(){function e(c,a){if(c.indexOf)return c.indexOf(a);for(var b=0,g=c.length;b<g;++b)if(c[b]===a)return b;return-1}function h(c,a){if(c.filter)return c.filter(a);for(var b=[],g=0,n=c.length;g<n;++g)a(c[g],g)&&b.push(c[g]);return b}Puma.arrayIndexOf=e;Puma.arrayFilter=h;Puma.operators={unary:{"#":function(c,a){if(a.getElementById){var b=a.getElementById(c.value);return b?[b]:[]}return h(a.getElementsByTagName("*"),function(b){return b.id==c.value})},".":function(c,a){if(a.getElementsByClassName)return[].slice.call(a.getElementsByClassName(c.value));
return h(a.getElementsByTagName("*"),function(b){return e(b.className.split(" "),c.value)>=0})},":":function(c,a){return Puma.operators.binary[":"](new Puma.AST.Tag("*"),c,a)},"::":function(c,a){return Puma.operators.binary["::"](new Puma.AST.Tag("*"),c,a)},"[":function(c,a){return Puma.operators.binary["["](new Puma.AST.Tag("*"),c,a)}},binary:{"#":function(c,a,b){var g=c.evaluate(b);if(b.getElementById)return c=b.getElementById(a.value),e(g,c)>=0?[c]:[];return h(b.getElementsByTagName("*"),function(b){return b.id==
a.value&&e(g,b)>=0})},".":function(c,a,b){var g=c.evaluate(b);if(b.getElementsByClassName)return h(b.getElementsByClassName(a.value),function(b){return e(g,b)>=0});return h(b.getElementsByTagName("*"),function(b){return e(b.className.split(" "),a.value)>=0&&e(g,b)>=0})},",":function(c,a,b){for(var c=c.evaluate(b),a=a.evaluate(b),b=0,g=a.length;b<g;++b)e(c,a[b])<0&&c.push(a[b]);return c},">":function(c,a,b){var g=c.evaluate(b);return h(a.evaluate(b),function(b){return e(g,b.parentNode)>=0})}," ":function(c,
a,b){var g=c.evaluate(b);return h(a.evaluate(b),function(b){for(;b=b.parentNode;)if(e(g,b)>=0)return!0;return!1})},"+":function(c,a,b){var g=c.evaluate(b);return h(a.evaluate(b),function(b){for(;b=b.previousSibling;)if(b.nodeType==1)return e(g,b)>=0})},"~":function(c,a,b){var g=c.evaluate(b);return h(a.evaluate(b),function(b){for(;b=b.previousSibling;)if(b.nodeType==1&&e(g,b)>=0)return!0;return!1})},":":function(c,a,b){var g=Puma.pseudoclasses;!g[a.value]&&!g[a.left.value]&&a.error("Unknown pseudoclass "+
(a.value!="("?a.value:a.left.value));return h(c.evaluate(b),function(c){if(a.value=="(")return g[a.left.value](c,a.right,b);return g[a.value](c)})},"::":function(c,a,b){var g=Puma.pseudoelements,n=0,d=[],e;g[a.value]||a.error("Unknown pseudoelement "+a.value);c=c.evaluate(b);for(b=c.length;n<b;++n)e=g[a.value](c[n]),e!=null&&d.push.apply(d,e);return d},"[":function(c,a,b){c=c.evaluate(b);if(a.arity=="binary")return Puma.operators.binary[a.value](c,a.left,a.right);a.evaluate(b);return h(c,function(b){return b.hasAttribute(a.value)})},
"=":function(c,a,b){return h(c,function(g){return g.getAttribute(a.value)==b.value})},"!=":function(c,a,b){return h(c,function(g){return g.getAttribute(a.value)!=b.value})},"^=":function(c,a,b){return h(c,function(g){return(g=g.getAttribute(a.value))&&g.indexOf(b.value)==0})},"$=":function(c,a,b){return h(c,function(g){return(g=g.getAttribute(a.value))&&g.lastIndexOf(b.value)==g.length-b.value.length})},"*=":function(c,a,b){return h(c,function(g){return(g=g.getAttribute(a.value))&&g.indexOf(b.value)>=
0})},"@=":function(c,a,b){return h(c,function(g){return(g=g.getAttribute(a.value))&&RegExp(b.value).test(g)})}}};var f=Puma.operators.binary,d=Puma.operators.unary;f[">"].precendence=f[" "].precendence=f["+"].precendence=f["~"].precendence=8;f[","].precendence=5;f["#"].noIter=f["."].noIter=f[","].noIter=f[">"].noIter=f[" "].noIter=f["+"].noIter=f["~"].noIter=f[":"].noIter=f["::"].noIter=f["["].noIter=d["#"].noIter=d["."].noIter=d[":"].noIter=d["::"].noIter=d["["].noIter=!0;Puma.pseudoclasses={contains:function(c,
a){var a=a.value,b=c.innerText||c.textContent||"";if(a.indexOf("/")==0&&a.lastIndexOf("/")==a.length-1)return RegExp(a.substring(1,a.length-1)).test(b);return b.indexOf(a)>=0},not:function(c,a,b){if(!a.notCache)a.notCache=a.evaluate(b);return e(a.notCache,c)<0},"first-child":function(c){return c.parentNode.children&&c==c.parentNode.children[0]},"last-child":function(c){var a=c.parentNode.children;return a&&c==a[a.length-1]},"nth-child":function(c,a){var b=a.value;if(b=="n")return!0;if(b=="odd")return e(c.parentNode.children,
c)%2==0;if(b=="even")return e(c.parentNode.children,c)%2==1;if(!a.nthChildCache)a.nthChildCache=b.length==1&&b!="+"?function(g){return e(g.parentNode.children,g)==b-1}:b=="+"?function(b){for(var c=e(b.parentNode.children,b),d=parseInt(a.right.value)-1,i=a.left.value.length>1?parseInt(a.left.value.length):0,f=0,b=b.parentNode.children.length;f<b;++f)if(c==f*i+d)return!0;return!1}:function(g){for(var c=e(g.parentNode.children,g)+1,a=parseInt(b),d=0,g=g.parentNode.children.length;d<g;++d)if(c==d*a)return!0;
return!1};return a.nthChildCache(c)}};Puma.pseudoelements={}})();
var Shrike=function(e,h){function f(b,g){return Puma(b,g)}function d(b,g){return function(c,a){var d=!0,e={};if(a.node!==h||a.nodes!==h){e=a;if(a.clone!==h)d=a.clone;a=a.node?a.node:a.nodes}f.isArray(a)||(a=[a]);for(var k=0,j=a.length;k<j;++k)b(c,a[k],d,e);g&&g(c,a,d,e)}}function c(b){return d(function(b,a,c,d){d.frag=d.frag||e.createDocumentFragment();d.frag.appendChild(a)},function(a,c,d,e){b(a,d?e.frag.cloneNode(!0):e.frag,e)})}var a={destroy:d(function(b,a){if(a=="self")b.parentNode.removeChild(b);
else if(a=="all")for(;b.lastChild;)b.removeChild(b.lastChild);else b.removeChild(a)}),top:c(function(b,a){b.insertBefore(a,b.firstChild)}),bottom:c(function(b,a){b.appendChild(a)}),before:c(function(b,a){b.parentNode.insertBefore(a,b)}),after:c(function(b,a){b.parentNode.insertBefore(a,b.nextSibling)})};f.declaration=function(b,a,c,d){return function(e,l){var k=[],j,m,p,q=0,t,r,s,u;if(l)k.push(e.length===h?[e]:e,l,{});else for(j in e)e.hasOwnProperty(j)&&k.push(Puma(j),e[j],{});for(t=k.length;q<t;++q){j=
k[q];m=k[++q];p=k[++q];s=0;for(u=j.length;s<u;++s){c&&c(j[s],p);for(r in m)if(m.hasOwnProperty(r))if(b.hasOwnProperty(r)&&typeof b[r]=="function")b[r](j[s],m[r],p);else a&&a(j[s],r,m[r],p);d&&d(j[s],p)}}return f}};f.merge=function(b){var a=arguments,c,d=a.length-1,e=1,f,h;typeof a[d]=="function"?h=a[d]:(h=function(b){return b},++d);for(;e<d;)for(f in c=a[e++],c)c.hasOwnProperty(f)&&(b[f]=h.call(c,c[f],f));return b};f.merge(f,{extend:function(){var b=[].slice.call(arguments);b.unshift({});return f.merge.apply(f,
b)},clone:function(b){var a={},c;for(c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a},object:function(b){function a(){}a.prototype=b;return new a},first:function(){for(var b=arguments,a=0,c=b.length;a<c;++a)if(b[a]!==h)return b[a];return null},inspect:function(b,a,c,d,e){function f(b){return b}var a=a||": ",d=d||f,e=e||f,h=[],j;for(j in b)b.hasOwnProperty(j)&&h.push([d(j),e(b[j])].join(a));return h.join(c||"\n")},toQueryString:function(b){var a=encodeURIComponent;return f.inspect(b,"=","&",a,a)},
bind:function(b,a,c,d){return function(){var e=[].slice.call(arguments);e.unshift.apply(e,c||[]);e.push.apply(e,d||[]);return b.apply(a,e)}},isArray:function(b){return{}.toString.call(b)=="[object Array]"},computedStyle:function(b,a){if(window.getComputedStyle)return e.defaultView.getComputedStyle(b,null).getPropertyValue(a.replace(/[A-Z]/,function(b){return"-"+b.toLowerCase()}));else if(b.currentStyle)return b.currentStyle[a];return 0},position:function(b){var a=0,c=0;do a+=b.offsetLeft,c+=b.offsetTop;
while(b=b.offsetParent);return{x:a,y:c}},size:function(b){return{height:b.offsetHeight,width:b.offsetWidth}},create:function(b){for(var a=Puma.Scanner.tokenize(b),c=e.createElement(a[0].value),d=1,i=arguments.length,l=1,k=a.length,j,m=e.createDocumentFragment();l<k;)switch(a[l++].value){case "#":c.id=a[l].value;break;case ".":f.attr(c,{"class":{add:a[l].value}});break;case "[":j={};j[a[l].value]=a[l+=2].value;f.attr(c,j);break;case ":":a[l].value=="contains"&&(c.innerHTML+=a[l+=2].value)}for(;d<i;)a=
arguments[d++],typeof a=="string"?c.innerHTML+=a:a.nodeType!==h?m.appendChild(a.cloneNode(!0)):a.clone!==h&&a.node!==h?m.appendChild(a.clone?a.node.cloneNode(!0):a.node):f.attr(c,a);c.appendChild(m);return c},modify:f.declaration(a,function(b,c,d){c=parseInt(c);c!=NaN&&a.before(b.children[c-1],d)}),attr:f.declaration({"class":function(b,a){if(typeof a=="string")b.className=a;else{var c=b.className.split(" "),d,e=0,f;if(a.add){d=a.add.split(" ");for(f=d.length;e<f;++e)c.push(d[e])}if(a.remove){d=a.remove.split(" ");
for(f=d.length;e<f;++e)for(var h=c,j=d[e],m=0,p=h.length;m<p;++m)h[m]===j&&h.splice(m,1)}c=c.join(" ");c.charAt(0)==" "&&(c=c.substring(1));b.className=c}},style:function(b,a){f.style(b,a)},on:function(b,a){if(f.on)f.on(b,a)},html:function(b,a){b.innerHTML=a},"for":function(b,a){b.htmlFor=a}},function(a,c,d){d===null?a.removeAttribute(c):a.setAttribute(c,d)}),style:f.declaration({},function(a,c,d){a.style[c.replace(/\-(\w)/g,function(a,b){return b.toUpperCase()})]=d})});return f}(document);
(function(e){function h(){d=!0;try{document.documentElement.doScroll("left")}catch(c){setTimeout(h,0);return}for(var a=0,b=f.length;a<b;++a)f[a]()}e.addEvent=function(c,a,b,d,e){var d=d||c,e=e||[],f=c[a],h=f;if(!f||!f.handlers)f=c[a]=function(){var a=0,b=e.slice.call(arguments),c=f.handlers,h=c.length-1;for(b.unshift.apply(b,e);a<h;++a)c[a].apply(d,b);if(h+1)return c[a].apply(d,b)},f.handlers=h?[h]:[];f.handlers.push(b);return b};e.removeEvent=function(c,a,b){var d,e=0;if(c[a]&&(d=c[a].handlers))for(c=
d.length;e<c;++e)d[e]==b&&d.splice(e,1);return b};var f=[],d=!1;e.ready=function(c){document.addEventListener?document.addEventListener("DOMContentLoaded",c,!1):(f.push(c),d||h());return e};e.on=e.declaration({},function(c,a,b){e.addEvent(c,"on"+a,b)});e.off=e.declaration({},function(c,a,b){e.removeEvent(c,"on"+a,b)})})(Shrike);
(function(e){function h(e,d,c,a){e.onreadystatechange=function(){if(e.readyState==4){var b,g,h;if(e.status==200){if(d.length==0)a.innerHTML=e.responseText;b=0;for(g=d.length;b<g;++b)if(h=d[b](a,e),typeof h=="string"){if(b==0)a.innerHTML="";a.innerHTML+=h}}else{b=0;for(g=c.length;b<g;++b)c[b](a,e)}}}}e.ajax=function(f,d){var c=[],a=[],b={};return e.declaration({url:function(a,c){b.url=c},success:function(a,b){c.push(b)},error:function(b,c){a.push(c)},get:function(d,f){var o=new XMLHttpRequest;o.open("GET",
[b.url,typeof f=="string"?f:e.toQueryString(f)].join("?"),!0);h(o,c,a,d);o.send(null)},post:function(d,f){var o=new XMLHttpRequest;o.open("POST",b.url,!0);o.setRequestHeader("Content-type","application/x-www-form-urlencoded");h(o,c,a,d);o.send(typeof f=="string"?f:e.toQueryString(f))}},function(){})(f,d)}})(Shrike);
(function(e){function h(d,c,a){c=c.replace(/\-(\w)/g,function(a,b){return b.toUpperCase()});if(a.from!==void 0)d.style[c]=a.from;if(typeof a=="string"||typeof a=="number")a={to:a};for(var b={from:""+e.first(a.from,e.computedStyle(d,c)),to:""+a.to,speed:e.first(a.speed,a.increment,5)/10,delay:e.first(a.delay,20),finishHandlers:a.finish?e.isArray(a.finish)?a.finish:[a.finish]:[],updateHandlers:a.update?e.isArray(a.update)?a.update:[a.update]:[]},g=[],f,h,i,l,k=1,j=a=0,m=b.from.length,p,q;a<m;++a){p=
b.from.charAt(a);q=b.from.charAt(a+1);if(p=="-"&&q>"/"&&q<":"||p>"/"&&p<":")break;g.push(p)}g=g.join("");h=parseFloat(b.from.substring(a));i=b.to.substring(a);if(i<1&&i>0)for(m=i.substring(i.indexOf(".")+1).length;j<m;++j)k*=10;i=parseFloat(i);h*=k;l=i<h;f=setInterval(function(){var a=0,e;if(!l&&h/k>=i||l&&h/k<=i){clearInterval(f);d.style[c]=b.to;for(e=b.finishHandlers.length;a<e;++a)b.finishHandlers[a](d)}else{h+=l?-b.speed:b.speed;d.style[c]=g+h/k+b.to.substring(b.to.indexOf(i)+(""+i).length);for(e=
b.updateHandlers.length;a<e;++a)b.updateHandlers[a](d)}},b.delay)}function f(d,c,a){function b(a){a=a||window.event;h.left=a.clientX-l+"px";h.top=a.clientY-k+"px"}function g(c){c=c||window.event;e.removeEvent(f,"onmousemove",b);e.removeEvent(f,"onmouseup",g);for(var h=0,i=a.length;h<i;++h)a[h](d,c)}var f=document,h=d.style,i=e.position(d),l=Math.abs(i.x-c.clientX),k=Math.abs(i.y-c.clientY);e.addEvent(f,"onmousemove",b);e.addEvent(f,"onmouseup",g)}e.animate=e.declaration({opacity:function(d,c){if(typeof c==
"string"||typeof c=="number")c={to:c};h(d,"opacity",e.extend(c,{to:c.to/100}));var a=e.extend(c,{from:c.from!==void 0?"alpha(opacity="+parseInt(c.from)+")":"alpha(opacity=100)",to:"alpha(opacity="+c.to+")",speed:e.first(c.speed,c.increment,5)*10});h(d,"filter",a)}},h);e.drag=e.declaration({handle:function(d,c,a){a.handle=typeof c=="string"?Puma(c):c},start:function(d,c,a){a.startHandlers=a.startHandlers||[];[].push.apply(a.startHandlers,e.isArray(c)?c:[c])},finish:function(d,c,a){a.finishHandlers=
a.finishHandlers||[];[].push.apply(a.finishHandlers,e.isArray(c)?c:[c])}},function(){},function(){},function(d,c){function a(a){a=a||window.event;c.startHandlers=c.startHandlers||[];for(var b=0,e=c.startHandlers.length;b<e;++b)c.startHandlers[b](d,a);f(d,a,c.finishHandlers||[]);return!1}if(c.handle)for(var b=0,g=c.handle.length;b<g;++b)e.addEvent(c.handle[b],"onmousedown",a);else e.addEvent(d,"onmousedown",a)})})(Shrike);
